export const metadata = {

  title: "Terms of Service — FedResume Pro",

  description: "Terms governing use of FedResume Pro."

};

export default function TermsPage() {

  return (

    <main className="max-w-3xl mx-auto px-6 py-16" style={{ fontFamily: "'Public Sans', system-ui, sans-serif" }}>

      <h1 style={{ fontFamily: "'Merriweather', Georgia, serif", fontSize: 36, fontWeight: 700, color: "#141414", letterSpacing: "-0.01em" }}>

        Terms of Service

      </h1>

      <div className="text-sm mt-2" style={{ color: "#5a5550" }}>
 Last updated: 5/4/2026

      </div>

      <div className="mt-10 space-y-6" style={{ fontSize: 16, lineHeight: 1.8, color: "#3a3530" }}>

        <section>

          <h2 style={{ fontFamily: "'Merriweather', Georgia, serif", fontSize: 22, fontWeight: 700, color: "#141414", marginBottom: 10 }}>

            1. Acceptance of Terms

          </h2>

          <p>

            By accessing or using FedResume Pro (the "Service"), operated by Justin Yost ("we," "us"), you agree to these Terms of Service. If you don't agree, please don't use the Service.

          </p>

        </section>

        <section>

          <h2 style={{ fontFamily: "'Merriweather', Georgia, serif", fontSize: 22, fontWeight: 700, color: "#141414", marginBottom: 10 }}>

            2. Description of Service

          </h2>

          <p>

            FedResume Pro is an AI-powered tool that analyzes a federal job posting against a candidate's resume and generates feedback, suggested rewrites, and ready-to-paste content. The Service is intended to assist applicants. It does not guarantee employment, interview selection, or any specific outcome.

          </p>
</section>

        <section>

          <h2 style={{ fontFamily: "'Merriweather', Georgia, serif", fontSize: 22, fontWeight: 700, color: "#141414", marginBottom: 10 }}>

            3. No Affiliation with Federal Agencies

          </h2>

          <p>

            FedResume Pro is an independent service. We are not affiliated with, endorsed by, or sponsored by USAJOBS, the U.S. Office of Personnel Management (OPM), the Department of Veterans Affairs, the U.S. Department of Defense, or any other federal agency.

          </p>

        </section>

        <section>

          <h2 style={{ fontFamily: "'Merriweather', Georgia, serif", fontSize: 22, fontWeight: 700, color: "#141414", marginBottom: 10 }}>

            4. Payment & Pricing

          </h2>

          <p>

            Paid features are billed as one-time charges in U.S. dollars at the prices displayed at the time of purchase. Payment is processed by Stripe; we never see or store your card details. Prices may change with notice; previously-purchased services are honored at the original price.

          </p>

        </section>

        <section>

          <h2 style={{ fontFamily: "'Merriweather', Georgia, serif", fontSize: 22, fontWeight: 700, color: "#141414", marginBottom: 10 }}>

            5. Refunds

          </h2>

          <p>

            We offer a 30-day no-questions-asked refund. See our <a href="/refunds" style={{ color: "#0f2444", textDecoration: "underline" }}>Refund Policy</a> for details.

          </p>

        </section>

        <section>

          <h2 style={{ fontFamily: "'Merriweather', Georgia, serif", fontSize: 22, fontWeight: 700, color: "#141414", marginBottom: 10 }}>

            6. AI-Generated Content

          </h2>

          <p>

            Resume analysis and rewrite content is generated by large language models (currently Anthropic's Claude). AI output may contain errors, omissions, or inaccuracies. You are responsible for reviewing all generated content for accuracy before submitting it as part of any federal job application. We are not liable for inaccuracies in AI-generated content or for outcomes of applications submitted using that content.

          </p>

          <p className="mt-3">

            <strong>Specific note on Merit Hiring essays (Federal Application Bundle):</strong> The four Merit Hiring essay drafts produced by the Bundle tier are intended as personalized starting points for you to edit. Per OPM's Merit Hiring Plan rules effective October 2025, the essays you ultimately submit to USAJOBS must be in your own words and reflect your authentic experience and views. You agree to meaningfully revise the AI-generated drafts before submitting them as part of any federal application. Submitting AI-generated content verbatim may violate OPM rules and is your responsibility, not ours.

          </p>

        </section>

        <section>

          <h2 style={{ fontFamily: "'Merriweather', Georgia, serif", fontSize: 22, fontWeight: 700, color: "#141414", marginBottom: 10 }}>

            7. Acceptable Use

          </h2>

          <p>

            You agree not to: (a) submit content that you don't have the right to submit, including resumes belonging to other people without their consent; (b) use the Service to generate fraudulent or knowingly misleading employment representations; (c) attempt to reverse-engineer, scrape, or abuse the Service; (d) use the Service in violation of any applicable law.

          </p>

        </section>

        <section>

          <h2 style={{ fontFamily: "'Merriweather', Georgia, serif", fontSize: 22, fontWeight: 700, color: "#141414", marginBottom: 10 }}>

            8. Intellectual Property

          </h2>

          <p>

            You retain all rights to the resume content you submit and to the AI-generated output produced for you. The FedResume Pro brand, design, and underlying code are owned by us and may not be copied or redistributed without permission.
</p>

        </section>

        <section>

          <h2 style={{ fontFamily: "'Merriweather', Georgia, serif", fontSize: 22, fontWeight: 700, color: "#141414", marginBottom: 10 }}>

            9. Disclaimer of Warranties

          </h2>

          <p>

            The Service is provided "as is" and "as available" without warranties of any kind, express or implied. We do not warrant that the Service will be uninterrupted, error-free, or that it will result in any particular employment outcome.

          </p>

        </section>

        <section>

          <h2 style={{ fontFamily: "'Merriweather', Georgia, serif", fontSize: 22, fontWeight: 700, color: "#141414", marginBottom: 10 }}>

            10. Limitation of Liability

          </h2>

          <p>

            To the maximum extent permitted by law, our total liability arising from your use of the Service is limited to the amount you paid us in the 12 months preceding the claim, or $50, whichever is greater. We are not liable for indirect, incidental, consequential, or punitive damages.

          </p>

        </section>
 <section>

          <h2 style={{ fontFamily: "'Merriweather', Georgia, serif", fontSize: 22, fontWeight: 700, color: "#141414", marginBottom: 10 }}>

            11. Changes to These Terms

          </h2>

          <p>

            We may update these Terms from time to time. The "Last updated" date above will reflect the latest version. Continued use of the Service after changes constitutes acceptance.

          </p>

        </section>

        <section>

          <h2 style={{ fontFamily: "'Merriweather', Georgia, serif", fontSize: 22, fontWeight: 700, color: "#141414", marginBottom: 10 }}>
   12. Governing Law

          </h2>

          <p>

            These Terms are governed by the laws of the State of Wisconsin, United States, without regard to conflict-of-law principles.

          </p>

        </section>

        <section>

          <h2 style={{ fontFamily: "'Merriweather', Georgia, serif", fontSize: 22, fontWeight: 700, color: "#141414", marginBottom: 10 }}>

            13. Contact
 </h2>

          <p>

            Questions about these Terms? Email <a href="mailto:hello@fedresumepro.com" style={{ color: "#0f2444", textDecoration: "underline" }}>hello@fedresumepro.com</a>.

          </p>

        </section>

      </div>

      <div className="mt-12 pt-8 border-t" style={{ borderColor: "#e5e0d6" }}>

        <a href="/" style={{ color: "#0f2444", fontWeight: 600 }}>← Back to home</a>

      </div>

    </main>

  );

}


